name: CI

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: CI on Windows
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      # - name: Install packages (Linux)
      #   if: runner.os == 'Linux'
      #   uses: awalsh128/cache-apt-pkgs-action@v1.4.3
      #   with:
      #     packages: libgtk-3-dev libxdo-dev libayatana-appindicator3-dev
      #     version: 1.0
      #     execute_install_scripts: true
      - uses: Swatinem/rust-cache@v2

      - name: cargo build
        run: cargo build

      - name: cargo fmt
        run: cargo fmt --all -- --check

      - name: cargo clippy
        run: cargo clippy -- -D warnings

      - name: cargo test
        run: cargo test

  typos:
    name: Typos
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: crate-ci/typos@v1.19.0

  cargo-machete:
    runs-on: ubuntu-latest
    steps:
      - uses: Swatinem/rust-cache@v2
      - uses: actions/checkout@v4
      - name: Machete
        uses: bnjbvr/cargo-machete@main
